#! /usr/bin/env python
import os
import glob
'''
 read the image filenames for cars and noncars into a text file list
 images are divided up into vehicles and non-vehicle subfolders (each of 
 which contain subfolders)
'''

def get_filenames(basedir, label, output_filename):
    # different folders represent different sources for images 
    # i.e., GTI, Kitti, generated by me
    image_types = os.listdir(basedir)
    itemnames = []
    # get all of the file names for all of the cars
    for imtype in image_types:
        itemnames.extend(glob.glob(basedir + "/" + imtype+'/*'))
    
    print('Number of " + label + " Images found:', len(itemnames))
    # now write the car file names to a text file, one filename per line
    with open(output_filename,'w') as f:
        for fn in itemnames:
            f.write(fn + '\n')
            
def main():
    get_filenames("vehicles", "Vehicles", "cars.txt")
    get_filenames("non-vehicles", "Non-Vehicles", "notcars.txt")

if __name__ == "__main__":
    main()